### PR TITLE
Disable bindgen default features

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by michaellass** [comment]
Sorry for the late reply. For some reason github did not notify me of this PR. Could you please elaborate on this change, i.e., what the change in behavior will be and why this is desired?

**Comment by michaellass** [comment]
Why do you change the caret expression of the version to a fixed version? What features are deactivated by this and why are they not required for this crate? Again: Could you please elaborate on this change, i.e., what the change in behavior will be and why this is desired? I won't merge changes that are not self-explanatory or explained.

**Comment by vorot93** [comment]
1) Caret are [default requirements in Cargo](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements)
2) Not sure about documentation, but those features [are not for e2p's context](https://rust-lang.github.io/rust-bindgen/command-line-usage.html).
3) No there won't be any change of behaviour.

**Comment by michaellass** [comment]
Thank you. Turns out that in bindgen 0.61 the command line interface was extracted into its own crate so that bindgen itself has now way fewer depdendencies: https://github.com/rust-lang/rust-bindgen/pull/2284
Features that are still disabled by this PR are logging and which-rustfmt which bring additional depdendencies on log and which (see https://github.com/rust-lang/rust-bindgen/blob/v0.61.0/bindgen/Cargo.toml#L30). So this change still reduces the dependency tree a bit.

I wasn't aware that caret and simple version specification are identical. Seems that simple version strings are now the recommended way to go: https://github.com/rust-lang/cargo/pull/10158

Merged with those additional information added to the commit message.

**Pull request merged**
